// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJX8dFWV_Zon0egDTMKC2lYDc0JAqwX8',
    appId: '1:621779756153:web:ee49d76d16a1ff706020a8',
    messagingSenderId: '621779756153',
    projectId: 'aadhyai',
    authDomain: 'aadhyai.firebaseapp.com',
    storageBucket: 'aadhyai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACphDji8wtZha1kqsLhIGnvHgZVAJEQP4',
    appId: '1:621779756153:android:8dafa724fce31b3f6020a8',
    messagingSenderId: '621779756153',
    projectId: 'aadhyai',
    storageBucket: 'aadhyai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4akFNbcubzAxZbM1dnMesQtI5pZG-gzo',
    appId: '1:621779756153:ios:578127f8f9b0bbf26020a8',
    messagingSenderId: '621779756153',
    projectId: 'aadhyai',
    storageBucket: 'aadhyai.firebasestorage.app',
    iosClientId: '621779756153-8hs7mblrubtjh4l7u6mca6vmcp7f478v.apps.googleusercontent.com',
    iosBundleId: 'com.example.aadhyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4akFNbcubzAxZbM1dnMesQtI5pZG-gzo',
    appId: '1:621779756153:ios:578127f8f9b0bbf26020a8',
    messagingSenderId: '621779756153',
    projectId: 'aadhyai',
    storageBucket: 'aadhyai.firebasestorage.app',
    iosClientId: '621779756153-8hs7mblrubtjh4l7u6mca6vmcp7f478v.apps.googleusercontent.com',
    iosBundleId: 'com.example.aadhyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkJX8dFWV_Zon0egDTMKC2lYDc0JAqwX8',
    appId: '1:621779756153:web:0115e249049e36b16020a8',
    messagingSenderId: '621779756153',
    projectId: 'aadhyai',
    authDomain: 'aadhyai.firebaseapp.com',
    storageBucket: 'aadhyai.firebasestorage.app',
  );
}
